# Generated by Django 5.0.6 on 2024-06-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_desc', models.CharField(max_length=500)),
                ('available_quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('Television', 'Television'), ('Refrigerator', 'Refrigerator'), ('Air-Conditioner', 'Air-Conditioner'), ('Washing-Machine', 'Washing-Machine')], max_length=50)),
                ('company', models.CharField(choices=[('Sony', 'Sony'), ('Lg', 'Lg'), ('Panasonic', 'panasonic'), ('Ifb', 'Ifb')], max_length=50)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('Silver', 'Silver'), ('Blue', 'Blue')], max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
