# Generated by Django 5.0.6 on 2024-06-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='Product_Images'),
        ),
    ]
