# Generated by Django 5.0.6 on 2024-06-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='Product_Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='Product_Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='Product_Images'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Product_Images'),
        ),
    ]
