# Generated by Django 5.0.6 on 2024-06-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.CharField(choices=[('Sony', 'Sony'), ('Lg', 'Lg'), ('Panasonic', 'panasonic'), ('Samsung', 'Samsung'), ('Ifb', 'Ifb')], max_length=50),
        ),
    ]
