# Generated by Django 5.0.6 on 2024-06-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
