# Generated by Django 5.0.6 on 2024-06-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='product_user',
        ),
    ]
