# Generated by Django 5.0.6 on 2024-06-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_user_cartitem_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_user',
        ),
    ]
