# Generated by Django 5.0.6 on 2024-06-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
